  - name: add postgresql apt-key
    apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present
    sudo: yes

  - name: copy pgdg.list file
    copy: src=pgdg.list dest=/etc/apt/sources.list.d/pgdg.list
    sudo: yes

  - name: update apt cache
    apt: update-cache=yes
    sudo: yes

  - name: install packages
    apt: pkg={{item}} state=present
    sudo: yes
    with_items:
      - make
      - python-dev
      - python-pip
      - python-psycopg2
      - python-yaml
      - postgresql-server-dev-9.3
      - postgresql-9.3
      - postgresql-contrib-9.3
      - postgresql-9.3-plproxy
      - postgresql-plpython-9.3
      - skytools3
      - skytools3-ticker
      - libv8-dev
      - pgxnclient
      - iotop
      - sysstat

  - name: create postgres log dir
    file: state=directory path={{postgres.log_dir if postgres is defined else "/var/log/postgresql"}} owner=postgres group=postgres
    sudo: yes

  - name: create postgres data dir
    file: state=directory path={{data_dir | default('/data')}} owner=postgres group=postgres
    sudo: yes

  - name: create postgres backup dir
    file: state=directory path={{postgres.backup_dir if postgres is defined else "/backup/incoming"}} owner=postgres group=postgres mode=777
    sudo: yes

  - name: copy postgresql.conf
    action: template src=postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf
    sudo: yes

  - name: copy pg_hba.conf
    copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
    sudo: yes

  - name: install russian locale ru_RU
    command: locale-gen ru_RU
    sudo: yes

  - name: install russian locale ru_RU.UTF-8
    command: locale-gen ru_RU.UTF-8
    sudo: yes

  - name: restart postgresql
    command: /etc/init.d/postgresql restart
    sudo: yes

  - name: install plv8
    command: pgxn install plv8
    sudo: yes

  - name: create plv8 language
    command: psql -c "CREATE EXTENSION IF NOT EXISTS plv8;" -d template1
    sudo: yes
    sudo_user: postgres

  - name: create plcoffee language
    command: psql -c "CREATE EXTENSION IF NOT EXISTS plcoffee;" -d template1
    sudo: yes
    sudo_user: postgres

  - name: create plpythonu language
    command: psql -c "CREATE EXTENSION IF NOT EXISTS plpythonu;" -d template1
    sudo: yes
    sudo_user: postgres
    
  - name: fix skytools path
    lineinfile: dest=/usr/lib/pymodules/python2.7/.path line="/usr/lib/pymodules/python2.7/skytools-3.0"
    sudo: yes

  - name: install pgview
    copy: src=pg_view.py dest=/usr/bin/pgview mode=777
    sudo: yes
